<?php
// This script and data application were generated by AppGini 5.10
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/user.php");
	include("$currDir/user_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('user');
	if(!$perm[0]){
		echo StyleSheet();
		echo "<div class=\"error\">".$Translation['tableAccessDenied']."</div>";
		echo '<script language="javaScript">setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "user";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`user`.`id`" => "id",
		"`user`.`nama`" => "nama",
		"`user`.`nokp`" => "nokp",
		"`user`.`pass`" => "pass",
		"`user`.`level`" => "level",
		"`user`.`type`" => "type"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`user`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`user`.`id`" => "id",
		"`user`.`nama`" => "nama",
		"`user`.`nokp`" => "nokp",
		"`user`.`pass`" => "pass",
		"`user`.`level`" => "level",
		"`user`.`type`" => "type"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`user`.`id`" => "ID",
		"`user`.`nama`" => "Nama",
		"`user`.`nokp`" => "Nokp",
		"`user`.`pass`" => "Pass",
		"`user`.`level`" => "Level",
		"`user`.`type`" => "Type"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`user`.`id`" => "id",
		"`user`.`nama`" => "nama",
		"`user`.`nokp`" => "nokp",
		"`user`.`pass`" => "pass",
		"`user`.`level`" => "level",
		"`user`.`type`" => "type"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`user` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 0;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 3;
	$x->TablePaginationAlignment = 0;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "user_view.php";
	$x->RedirectAfterInsert = "user_view.php?SelectedID=#ID#";
	$x->TableTitle = "User";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`user`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Nama", "Nokp", "Pass", "Level", "Type");
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	$x->Template = 'templates/user_templateTV.html';
	$x->SelectedTemplate = 'templates/user_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `user`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='user' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `user`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='user' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`user`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: user_init
	$render=TRUE;
	if(function_exists('user_init')){
		$args=array();
		$render=user_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: user_header
	$headerCode='';
	if(function_exists('user_header')){
		$args=array();
		$headerCode=user_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include("$currDir/header.php"); 
	}else{
		ob_start(); include("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: user_footer
	$footerCode='';
	if(function_exists('user_footer')){
		$args=array();
		$footerCode=user_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include("$currDir/footer.php"); 
	}else{
		ob_start(); include("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?><div style="text-align: center; font-size: 10px;">Powered by <a href="http://bigprof.com/appgini/" target="_blank">BigProf AppGini 5.10</a></div>
