<?php

// Data functions for table user

// This script and data application were generated by AppGini 5.10
// Download AppGini for free from http://bigprof.com/appgini/download/

function user_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('user');
	if(!$arrPerm[1]){
		return 0;
	}

	$data['nama'] = makeSafe($_POST['nama']);
	$data['nokp'] = makeSafe($_POST['nokp']);
	$data['pass'] = makeSafe($_POST['pass']);
	$data['level'] = makeSafe($_POST['level']);
	$data['type'] = makeSafe($_POST['type']);

	// hook: user_before_insert
	if(function_exists('user_before_insert')){
		$args=array();
		if(!user_before_insert($data, getMemberInfo(), $args)){ return FALSE; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `user` set       `nama`=' . (($data['nama'] !== '' && $data['nama'] !== NULL) ? "'{$data['nama']}'" : 'NULL') . ', `nokp`=' . (($data['nokp'] !== '' && $data['nokp'] !== NULL) ? "'{$data['nokp']}'" : 'NULL') . ', `pass`=' . (($data['pass'] !== '' && $data['pass'] !== NULL) ? "'{$data['pass']}'" : 'NULL') . ', `level`=' . (($data['level'] !== '' && $data['level'] !== NULL) ? "'{$data['level']}'" : 'NULL') . ', `type`=' . (($data['type'] !== '' && $data['type'] !== NULL) ? "'{$data['type']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"user_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=mysql_insert_id();

	// hook: user_after_insert
	if(function_exists('user_after_insert')){
		$res = sql("select * from `user` where `id`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = $row;
		}
		$data['selectedID']=$recID;
		$args=array();
		if(!user_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='user', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function user_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('user');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='user' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='user' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return FALSE;
	}

	// hook: user_before_delete
	if(function_exists('user_before_delete')){
		$args=array();
		if(!user_before_delete($selected_id, $skipChecks, getMemberInfo(), $args)){ return FALSE; }
	}

	sql("delete from `user` where `id`='$selected_id'", $eo);

	// hook: user_after_delete
	if(function_exists('user_after_delete')){
		$args=array();
		user_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='user' and pkValue='$selected_id'", $eo);
}

function user_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('user');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='user' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='user' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return;
	}

	$data['nama'] = makeSafe($_POST['nama']);
	$data['nokp'] = makeSafe($_POST['nokp']);
	$data['pass'] = makeSafe($_POST['pass']);
	$data['level'] = makeSafe($_POST['level']);
	$data['type'] = makeSafe($_POST['type']);
	$data['selectedID']=makeSafe($selected_id);

	// hook: user_before_update
	if(function_exists('user_before_update')){
		$args=array();
		if(!user_before_update($data, getMemberInfo(), $args)){ return FALSE; }
	}

	$o=array('silentErrors' => true);
	sql('update `user` set       `nama`=' . (($data['nama'] !== '' && $data['nama'] !== NULL) ? "'{$data['nama']}'" : 'NULL') . ', `nokp`=' . (($data['nokp'] !== '' && $data['nokp'] !== NULL) ? "'{$data['nokp']}'" : 'NULL') . ', `pass`=' . (($data['pass'] !== '' && $data['pass'] !== NULL) ? "'{$data['pass']}'" : 'NULL') . ', `level`=' . (($data['level'] !== '' && $data['level'] !== NULL) ? "'{$data['level']}'" : 'NULL') . ', `type`=' . (($data['type'] !== '' && $data['type'] !== NULL) ? "'{$data['type']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="user_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: user_after_update
	if(function_exists('user_after_update')){
		$res = sql("SELECT * FROM `user` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = mysql_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!user_after_update($data, getMemberInfo(), $args)){ return FALSE; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='user' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function user_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('user');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='user' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='user' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `user` where `id`='".makeSafe($selected_id)."'", $eo);
		$row = mysql_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/user_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/user_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($arrPerm[1]){ // allow insert?
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="positive" id="insert" name="insert_x" value="1" onclick="return user_validateData();"><img src="addNew.gif" /> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="positive" id="insert" name="insert_x" value="1" onclick="return user_validateData();"><img src="addNew.gif" /> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'parent.Modalbox.hide(); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		$templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><img src="print-preview.gif" /> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="positive" id="update" name="update_x" value="1" onclick="return user_validateData();"><img src="update.gif" /> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

			// set records to read only if user can't insert new records
			if(!$arrPerm[1]){
				$jsReadOnly.="\n\n\tif(document.getElementsByName('id').length){ document.getElementsByName('id')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('nama').length){ document.getElementsByName('nama')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('nokp').length){ document.getElementsByName('nokp')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('pass').length){ document.getElementsByName('pass')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('level').length){ document.getElementsByName('level')[0].readOnly=true; }\n";
				$jsReadOnly.="\n\n\tif(document.getElementsByName('type').length){ document.getElementsByName('type')[0].readOnly=true; }\n";

				$noUploads=true;
			}
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="negative" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><img src="delete.gif" /> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><img src="deselect.gif" /> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><img src="deselect.gif" /> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// process combos

	// process foreign key links
	if($selected_id){
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(nama)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(nokp)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(pass)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(level)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(type)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', htmlspecialchars($row['id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(nama)%%>', htmlspecialchars($row['nama'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(nama)%%>', urlencode($urow['nama']), $templateCode);
		$templateCode=str_replace('<%%VALUE(nokp)%%>', htmlspecialchars($row['nokp'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(nokp)%%>', urlencode($urow['nokp']), $templateCode);
		$templateCode=str_replace('<%%VALUE(pass)%%>', htmlspecialchars($row['pass'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(pass)%%>', urlencode($urow['pass']), $templateCode);
		$templateCode=str_replace('<%%VALUE(level)%%>', htmlspecialchars($row['level'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(level)%%>', urlencode($urow['level']), $templateCode);
		$templateCode=str_replace('<%%VALUE(type)%%>', htmlspecialchars($row['type'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type)%%>', urlencode($urow['type']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(nama)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(nama)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(nokp)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(nokp)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(pass)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(pass)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(level)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(level)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(type)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>\n";
		$arrTables=getTableList();
		foreach($arrTables as $name=>$caption){
			$templateCode.="\tif(document.getElementById('".$name."_link')!=undefined){\n";
			$templateCode.="\t\tdocument.getElementById('".$name."_link').style.visibility='visible';\n";
			$templateCode.="\t}\n";
			for($i=1; $i<10; $i++){
				$templateCode.="\tif(document.getElementById('".$name."_plink$i')!=undefined){\n";
				$templateCode.="\t\tdocument.getElementById('".$name."_plink$i').style.visibility='visible';\n";
				$templateCode.="\t}\n";
			}
		}

		$templateCode.=$jsReadOnly;

		if(!$selected_id){
		}

		$templateCode.="\n</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: user_dv
	if(function_exists('user_dv')){
		$args=array();
		user_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>